//
//  StudentLocation.swift
//  OnTheMap-UIKit
//
//  Created by Mohammed Tangestani on 10/26/20.
//

import Foundation
import MapKit

struct StudentLocation: Codable {
    let objectId: String  // an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
    let uniqueKey: String  // an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
    let firstName: String  // the first name of the student which matches their Udacity profile first name OR an anonymized name hardcoded in your app (see above)
    let lastName: String  // the last name of the student which matches their Udacity profile last name OR an anonymized name hardcoded in your app (see above)
    let mapString: String  // the location string used for geocoding the student location
    let mediaURL: String  //  the URL provided by the student
    let latitude: Double  // the latitude of the student location (ranges from -90 to 90)
    let longitude: Double  // the longitude of the student location (ranges from -180 to 180)
    let createdAt: String  // the date when the student location was created
    let updatedAt: String  // the date when the student location was last updated
    
    var name: String {
        "\(firstName) \(lastName)"
    }
    
    var coordinate: CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    }
    
    var url: URL? {
        URL(string: mediaURL)
    }
}
